export type PersistedRiskFlag={code:string;message:string;evidence:string;severity:string};
export type RiskPresentation={
  mode:'TECHNICAL_ERROR'|'PENDING'|'DECISION';decision:string|null;score:number|null;
  summary:string;recommendation:string|null;flags:PersistedRiskFlag[];passedChecks:string[];
};

function upper(value:unknown){return String(value||'').trim().toUpperCase()}

export function buildRiskPresentation(invoice:Record<string,any>):RiskPresentation {
  const aiStatus=upper(invoice.ai_status),status=upper(invoice.status);
  const technical=aiStatus==='ERROR'||['ERROR','EXTRACTION_FAILED'].includes(status);
  if(technical)return {mode:'TECHNICAL_ERROR',decision:null,score:null,summary:'Technical processing error. Risk Agent was not executed.',recommendation:null,flags:[],passedChecks:[]};

  const decision=upper(invoice.risk_decision);
  if(!['AUTO_PROPOSE','ESCALATE','BLOCK'].includes(decision))return {mode:'PENDING',decision:null,score:null,summary:'Risk Agent decision is pending.',recommendation:null,flags:[],passedChecks:[]};

  const flags:Array<PersistedRiskFlag>=(Array.isArray(invoice.risk_flags)?invoice.risk_flags:[]).map(flag=>({
    code:String(flag?.code||'UNKNOWN'),message:String(flag?.message||''),evidence:String(flag?.evidence||''),severity:upper(flag?.severity)||'UNKNOWN',
  }));
  const codes=new Set(flags.map(flag=>flag.code));
  const passedChecks:string[]=[];
  if(invoice.invoice_number&&!codes.has('DUPLICATE_INVOICE_NUMBER'))passedChecks.push('Invoice number unique');
  if(invoice.recipient_wallet&&!codes.has('MISSING_RECIPIENT_WALLET'))passedChecks.push('Recipient wallet present');
  if(!codes.has('WALLET_MISMATCH'))passedChecks.push('No vendor wallet mismatch detected');
  if(!codes.has('AMOUNT_ANOMALY')&&!codes.has('PAYMENT_LIMIT'))passedChecks.push('Amount within expected range');
  if(Array.isArray(invoice.missing_fields)&&invoice.missing_fields.length===0)passedChecks.push('Required fields complete');

  const recommendation={
    AUTO_PROPOSE:'Invoice passed the automated policy checks and is eligible for a human-controlled on-chain proposal.',
    ESCALATE:'Invoice requires Manager review. No Casper proposal has been submitted.',
    BLOCK:'Critical policy violation detected. Proposal creation and blockchain submission are blocked.',
  }[decision]||null;
  return {mode:'DECISION',decision,score:Number.isFinite(Number(invoice.risk_score))?Number(invoice.risk_score):null,summary:'Decision generated by deterministic policy checks from persisted invoice facts.',recommendation,flags,passedChecks};
}
